### ISSUE TITLE
[Feature] Configurable individual warp markers

### ISSUE THREAD

**Issue by USBCharger** [pop4959/BlueMap-Essentials#11]
Title says it all more or less lol, maybe with the directory being inside the essentials directory where the images are stored currently as custom or smth?

**Comment by pop4959** [comment]
Added by https://github.com/pop4959/BlueMap-Essentials/commit/ba33c6dd308764b7dffb8f41e448a43d2a16b86d :)

Thanks @TechnicJelle!
