### ISSUE TITLE
[Feature] Auto refresh/actualize Player home markers in browser

### ISSUE THREAD

**Issue by ghost** [pop4959/BlueMap-Essentials#4]
[Feature] 
- Auto refresh/actualize map in browser when Player logins or creates new home/(No manual refresh in browser. Dont know if thats  problem on BlueMap API side or Plugin side)

**Comment by pop4959** [comment]
There's not anything I can do at the moment for this, as I understand it BlueMap doesn't currently auto-refresh. I think Blue is planning to look into this in the future. For the time being, just reload the page.
