### ISSUE TITLE
When disabling homes in the config, the slider still exists in the sidebar

### ISSUE THREAD

**Issue by rmellis** [pop4959/BlueMap-Essentials#5]
The slider has no functionality but it still remains in the sidebar when removed from the config.
![image](https://user-images.githubusercontent.com/41447552/106640902-849b7f80-657e-11eb-8f09-19dc6ea7d8fa.png)

**Comment by hkkongou** [comment]
same
i was expecting this function is closed and no one can toggle on or off

**Comment by hkkongou** [comment]
> The slider has no functionality but it still remains in the sidebar when removed from the config.
> ![image](https://user-images.githubusercontent.com/41447552/106640902-849b7f80-657e-11eb-8f09-19dc6ea7d8fa.png)

no, thats not how it works

i found out that the enable setting only toggle whether this plugin check and pass the data to bluemap

if you already have data of home and warps and you want to remove them, you need to go to bluemap/web/data/markers.conf to remove it yourself

**Comment by rmellis** [comment]
> > The slider has no functionality but it still remains in the sidebar when removed from the config.
> > ![image](https://user-images.githubusercontent.com/41447552/106640902-849b7f80-657e-11eb-8f09-19dc6ea7d8fa.png)
> 
> no, thats not how it works
> 
> i found out that the enable setting only toggle whether this plugin check and pass the data to bluemap
> 
> if you already have data of home and warps and you want to remove them, you need to go to bluemap/web/data/markers.conf to remove it yourself

i forked it on here a few weeks back and striped the homes out completely but yeah that works too

**Comment by pop4959** [comment]
Sorry about that guys, was fairly busy and forgot this issue existed. Just pushed a new version of the plugin to Spigot which should fix this issue: [https://www.spigotmc.org/resources/bluemap-essentials.84365/](https://www.spigotmc.org/resources/bluemap-essentials.84365/)
