### ISSUE TITLE
The plugin is very unreliable in my use.

### ISSUE THREAD

**Issue by DoTheEvo** [pop4959/BlueMap-Essentials#7]
Sometimes it works sometimes it does not.
For one player it can be rock solid, it can completely ignore two others...

[The server](https://github.com/DoTheEvo/selfhosted-apps-docker/tree/master/minecraft) is on these plugins too: ActionHealth, AntiPopup, BlueMap, Essentials, EssentialsSpawn, Multiverse-Core, Multiverse-Inventories, Multiverse-Portals, NoChatReports, spark

I assume the plugin is getting data from /plugins/Essentials/userdata/ files
And I checked and homes are set there.
It probably put that data through api to bluemap, but I dunno where can I check if they are stored. They are not in per world config files in marker-sets. 

Anyway, for now I set up homes manually.

**Comment by pop4959** [comment]
Sorry to hear that this plugin is unreliable for you, though I haven't had any reports from anyone so far with these issues. To be able to look into this I will need userdata files from Essentials for the players that are not being displayed.

If you would like to reach out directly I can be found on the [BlueMap Discord](https://bluecolo.red/map-discord) (you can ping me in the #3rd-party-support channel), and we can troubleshoot further. Thanks!

**Comment by DoTheEvo** [comment]
sry, not enough time or drive to dig too much in to this... if no other reports then its just some issue on my side

**Comment by pop4959** [comment]
No worries. If you're still having issues please do reach out though.

Thanks for closing the issue, if it becomes clear that this is actually a bug we can re-open with the appropriate follow up.
